parameters:
    base.service.class: BaseBundle\Base\BaseService
    base.storage.class: BaseBundle\Base\BaseStorage
    base.type.class: BaseBundle\Base\BaseType

services:

    base.service:
        class: '%base.service.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    base.storage:
        class: '%base.storage.class%'
        abstract: true
        calls:
          - [setConnection, ["@doctrine.dbal.default_connection"]]

    base.type:
        class: '%base.type.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]
