parameters:
    base.oauth_user_provider.class: BaseBundle\Provider\OAuthUserProvider
    hwi_oauth.account.connector.class: BaseBundle\Connect\AccountConnect

services:

    base.oauth_user_provider:
        class: '%base.oauth_user_provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    hwi_oauth.account.connector:
        class: '%hwi_oauth.account.connector.class%'
