parameters:
    base.oauth_user_provider.class: BaseBundle\Provider\OAuthUserProvider
    hwi_oauth.account.connector.class: BaseBundle\Connect\AccountConnect
    pagerfanta.view.domajax.class: BaseBundle\Pagerfanta\View\DomajaxView

services:

    base.oauth_user_provider:
        class: '%base.oauth_user_provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    hwi_oauth.account.connector:
        class: '%hwi_oauth.account.connector.class%'

    pagerfanta.view.domajax:
        class: '%pagerfanta.view.domajax.class%'
        public: false
        tags:
            - { name: pagerfanta.view, alias: domajax }
